pipeline:
  name: harness-lab
  identifier: harness_lab_XZSXpDWk
  projectIdentifier: harnesstest1
  orgIdentifier: default
  stages:
    - stage:
        identifier: hello_stage
        name: Hello - CI Stage
        type: CI
        spec:
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessk8sconnector
              namespace: harness-runners
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: hello_world_run
                  name: Hello World Run
                  type: Run
                  timeout: 10m
                  spec:
                    connectorRef: harnessk8sconnector
                    image: alpine
                    shell: Sh
                    command: echo 'HELLO WORLD'
            rollbackSteps: []
  description: This pipeline was generated by Harness AI on 2025-11-27 18:17:03 UTC by Danilo Oliveira.
  tags:
    ai_generated: "true"
    jenkins_migrated: "true"
    migrated_using: jenkins-plugin-AI-harness
  properties:
    ci:
      codebase:
        repoName: hello-app
        build: <+input>
        sparseCheckout: []
